-- AlterEnum: Add ROOFING to PipelineType
ALTER TYPE "PipelineType" ADD VALUE IF NOT EXISTS 'ROOFING';

-- AlterEnum: Add roofing stages to LeadStage
ALTER TYPE "LeadStage" ADD VALUE IF NOT EXISTS 'ROOF_NEW_REQUEST';
ALTER TYPE "LeadStage" ADD VALUE IF NOT EXISTS 'ROOF_INSPECTION';
ALTER TYPE "LeadStage" ADD VALUE IF NOT EXISTS 'ROOF_QUOTE';
ALTER TYPE "LeadStage" ADD VALUE IF NOT EXISTS 'ROOF_APPROVED';
ALTER TYPE "LeadStage" ADD VALUE IF NOT EXISTS 'ROOF_MATERIALS';
ALTER TYPE "LeadStage" ADD VALUE IF NOT EXISTS 'ROOF_SCHEDULED';
ALTER TYPE "LeadStage" ADD VALUE IF NOT EXISTS 'ROOF_IN_PROGRESS';
ALTER TYPE "LeadStage" ADD VALUE IF NOT EXISTS 'ROOF_COMPLETED';
ALTER TYPE "LeadStage" ADD VALUE IF NOT EXISTS 'ROOF_INVOICED';
