export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  SALES_REP = 'SALES_REP',
  REFERRAL = 'REFERRAL',
}

export enum LeadStage {
  NEW_LEAD = 'NEW_LEAD',
  REQUEST_DESIGN = 'REQUEST_DESIGN',
  DESIGN_IN_PROGRESS = 'DESIGN_IN_PROGRESS',
  DESIGN_READY = 'DESIGN_READY',
  PENDING_SIGNATURE = 'PENDING_SIGNATURE',
  SIT = 'SIT',
  WON = 'WON',
  LOST = 'LOST',
  SITE_AUDIT_PENDING = 'SITE_AUDIT_PENDING',
  ENGINEERING_DESIGN = 'ENGINEERING_DESIGN',
  PROPOSAL_REVIEW = 'PROPOSAL_REVIEW',
  INSTALL_READY = 'INSTALL_READY',
  INSTALL_SCHEDULED = 'INSTALL_SCHEDULED',
  INSTALL_COMPLETE = 'INSTALL_COMPLETE',
  CANCELLED = 'CANCELLED',
}

export enum LeadSource {
  DOOR_KNOCK = 'DOOR_KNOCK',
  COLD_CALL = 'COLD_CALL',
  REFERRAL = 'REFERRAL',
  EVENT = 'EVENT',
  PUBLIC_FORM = 'PUBLIC_FORM',
  WEBSITE = 'WEBSITE',
  OTHER = 'OTHER',
}

export enum RoofCondition {
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  POOR = 'POOR',
  UNKNOWN = 'UNKNOWN',
}

export enum PropertyType {
  RESIDENTIAL = 'RESIDENTIAL',
  COMMERCIAL = 'COMMERCIAL',
}

export enum DesignType {
  AI_DESIGN = 'AI_DESIGN',
  MANUAL_DESIGN = 'MANUAL_DESIGN',
}

export enum DesignStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum AppointmentType {
  SITE_AUDIT = 'SITE_AUDIT',
  INSTALLATION = 'INSTALLATION',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RESCHEDULED = 'RESCHEDULED',
}

export enum CommissionType {
  M1 = 'M1',
  M2 = 'M2',
  M3 = 'M3',
}

export enum CommissionStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  PAID = 'PAID',
  VOIDED = 'VOIDED',
}

export enum DocumentType {
  UTILITY_BILL = 'UTILITY_BILL',
  ROOF_IMAGE = 'ROOF_IMAGE',
  DESIGN_RENDER = 'DESIGN_RENDER',
  CONTRACT = 'CONTRACT',
  ID_DOCUMENT = 'ID_DOCUMENT',
  OTHER = 'OTHER',
}

export enum ActivityType {
  STAGE_CHANGE = 'STAGE_CHANGE',
  NOTE_ADDED = 'NOTE_ADDED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  ASSIGNMENT_CHANGED = 'ASSIGNMENT_CHANGED',
  SCORE_UPDATED = 'SCORE_UPDATED',
  DESIGN_REQUESTED = 'DESIGN_REQUESTED',
  DESIGN_COMPLETED = 'DESIGN_COMPLETED',
  APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
  APPOINTMENT_COMPLETED = 'APPOINTMENT_COMPLETED',
  COMMISSION_CALCULATED = 'COMMISSION_CALCULATED',
  EMAIL_SENT = 'EMAIL_SENT',
  CALL_LOGGED = 'CALL_LOGGED',
  HUBSPOT_SYNCED = 'HUBSPOT_SYNCED',
}
