export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  SALES_REP = 'SALES_REP',
  REFERRAL = 'REFERRAL',
}

export enum LeadStatus {
  ACTIVE = 'ACTIVE',
  LOST = 'LOST',
  CANCELLED = 'CANCELLED',
}

export enum PipelineType {
  CLOSER = 'CLOSER',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  FINANCE = 'FINANCE',
  MAINTENANCE = 'MAINTENANCE',
}

export enum LeadStage {
  // Closer Pipeline (Sales Team)
  NEW_LEAD = 'NEW_LEAD',
  ALREADY_CALLED = 'ALREADY_CALLED',
  CONNECTED = 'CONNECTED',
  REQUEST_DESIGN = 'REQUEST_DESIGN',
  DESIGN_IN_PROGRESS = 'DESIGN_IN_PROGRESS',
  DESIGN_READY = 'DESIGN_READY',
  WON = 'WON',

  // Project Manager Pipeline (Ops Team)
  SITE_AUDIT = 'SITE_AUDIT',
  PROGRESS_REVIEW = 'PROGRESS_REVIEW',
  NTP = 'NTP',
  ENGINEERING = 'ENGINEERING',
  PERMIT_AND_ICE = 'PERMIT_AND_ICE',
  FINAL_APPROVAL = 'FINAL_APPROVAL',
  INSTALL_READY = 'INSTALL_READY',
  INSTALL = 'INSTALL',
  COMMISSION = 'COMMISSION',
  SITE_COMPLETE = 'SITE_COMPLETE',
  INITIAL_SUBMISSION_AND_INSPECTION = 'INITIAL_SUBMISSION_AND_INSPECTION',
  WAITING_FOR_PTO = 'WAITING_FOR_PTO',
  FINAL_SUBMISSION = 'FINAL_SUBMISSION',
  CUSTOMER_SUCCESS = 'CUSTOMER_SUCCESS',

  // Finance Pipeline (Finance Team)
  FIN_TICKETS_OPEN = 'FIN_TICKETS_OPEN',
  FIN_IN_PROGRESS = 'FIN_IN_PROGRESS',
  FIN_POST_INITIAL_NURTURE = 'FIN_POST_INITIAL_NURTURE',
  FIN_TICKETS_CLOSED = 'FIN_TICKETS_CLOSED',

  // Maintenance Pipeline (Maintenance Team — on demand)
  MAINT_TICKETS_OPEN = 'MAINT_TICKETS_OPEN',
  MAINT_IN_PROGRESS = 'MAINT_IN_PROGRESS',
  MAINT_POST_INSTALL_NURTURE = 'MAINT_POST_INSTALL_NURTURE',
  MAINT_TICKETS_CLOSED = 'MAINT_TICKETS_CLOSED',
}

export enum LeadSource {
  DOOR_KNOCK = 'DOOR_KNOCK',
  COLD_CALL = 'COLD_CALL',
  REFERRAL = 'REFERRAL',
  EVENT = 'EVENT',
  PUBLIC_FORM = 'PUBLIC_FORM',
  WEBSITE = 'WEBSITE',
  OTHER = 'OTHER',
}

export enum RoofCondition {
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  POOR = 'POOR',
  UNKNOWN = 'UNKNOWN',
}

export enum PropertyType {
  RESIDENTIAL = 'RESIDENTIAL',
  COMMERCIAL = 'COMMERCIAL',
}

export enum DesignType {
  AI_DESIGN = 'AI_DESIGN',
  MANUAL_DESIGN = 'MANUAL_DESIGN',
}

export enum DesignStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum AppointmentType {
  SITE_AUDIT = 'SITE_AUDIT',
  INSTALLATION = 'INSTALLATION',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RESCHEDULED = 'RESCHEDULED',
}

export enum CommissionType {
  M1 = 'M1',
  M2 = 'M2',
  M3 = 'M3',
}

export enum CommissionStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  PAID = 'PAID',
  VOIDED = 'VOIDED',
}

export enum DocumentType {
  UTILITY_BILL = 'UTILITY_BILL',
  ROOF_IMAGE = 'ROOF_IMAGE',
  DESIGN_RENDER = 'DESIGN_RENDER',
  CONTRACT = 'CONTRACT',
  ID_DOCUMENT = 'ID_DOCUMENT',
  OTHER = 'OTHER',
}

export enum ActivityType {
  STAGE_CHANGE = 'STAGE_CHANGE',
  NOTE_ADDED = 'NOTE_ADDED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  ASSIGNMENT_CHANGED = 'ASSIGNMENT_CHANGED',
  SCORE_UPDATED = 'SCORE_UPDATED',
  DESIGN_REQUESTED = 'DESIGN_REQUESTED',
  DESIGN_COMPLETED = 'DESIGN_COMPLETED',
  APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
  APPOINTMENT_COMPLETED = 'APPOINTMENT_COMPLETED',
  COMMISSION_CALCULATED = 'COMMISSION_CALCULATED',
  EMAIL_SENT = 'EMAIL_SENT',
  CALL_LOGGED = 'CALL_LOGGED',
  HUBSPOT_SYNCED = 'HUBSPOT_SYNCED',
}
