import { Injectable, Logger, Inject } from '@nestjs/common';
import { QueryBus } from '@nestjs/cqrs';
import { EmailService } from '../../../../infrastructure/email/email.service';
import { GetScoreboardQuery } from '../queries/get-scoreboard.handler';

interface ScoreboardEntry {
  userId: string;
  userName: string;
  wonDeals: number;
  totalCommission: number;
}

@Injectable()
export class ScoreboardEmailService {
  private readonly logger = new Logger(ScoreboardEmailService.name);

  constructor(
    private readonly queryBus: QueryBus,
    private readonly emailService: EmailService,
  ) {}

  async sendScoreboardEmail(
    startDate: Date,
    endDate: Date,
    recipientEmails: string[],
  ): Promise<{ sent: boolean; recipientCount: number }> {
    const scoreboard: ScoreboardEntry[] = await this.queryBus.execute(
      new GetScoreboardQuery(
        startDate.toISOString(),
        endDate.toISOString(),
        50,
      ),
    );

    const html = this.buildEmailHtml(scoreboard, startDate, endDate);

    const formatDate = (d: Date) => d.toISOString().split('T')[0];
    const subject = `ecoLoop Scoreboard — ${formatDate(startDate)} to ${formatDate(endDate)}`;

    const sent = await this.emailService.send({
      to: recipientEmails,
      subject,
      html,
    });

    if (sent) {
      this.logger.log(
        `Scoreboard email sent to ${recipientEmails.length} recipient(s)`,
      );
    } else {
      this.logger.warn('Scoreboard email failed to send');
    }

    return { sent, recipientCount: recipientEmails.length };
  }

  private buildEmailHtml(
    scoreboard: ScoreboardEntry[],
    startDate: Date,
    endDate: Date,
  ): string {
    const formatDate = (d: Date) => d.toISOString().split('T')[0];
    const formatCurrency = (v: number) =>
      new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
      }).format(v);

    const rows = scoreboard
      .map(
        (entry, index) => `
        <tr style="border-bottom: 1px solid #E5E7EB;">
          <td style="padding: 12px 16px; text-align: center; font-weight: ${index < 3 ? 'bold' : 'normal'};">${index + 1}</td>
          <td style="padding: 12px 16px;">${entry.userName}</td>
          <td style="padding: 12px 16px; text-align: center;">${entry.wonDeals}</td>
          <td style="padding: 12px 16px; text-align: right;">${formatCurrency(entry.totalCommission)}</td>
        </tr>`,
      )
      .join('');

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body style="margin: 0; padding: 0; background-color: #F8FAFB; font-family: 'Inter', Arial, sans-serif;">
  <div style="max-width: 600px; margin: 0 auto; padding: 32px 16px;">
    <div style="background-color: #FFFFFF; border-radius: 12px; border: 1px solid #E5E7EB; overflow: hidden; box-shadow: 0 1px 2px rgba(0,0,0,0.05);">
      <div style="background-color: #00897B; padding: 24px 32px; color: #FFFFFF;">
        <h1 style="margin: 0; font-size: 22px; font-weight: 600;">Scoreboard Report</h1>
        <p style="margin: 8px 0 0; font-size: 14px; opacity: 0.9;">${formatDate(startDate)} to ${formatDate(endDate)}</p>
      </div>
      <div style="padding: 0;">
        <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
          <thead>
            <tr style="background-color: #F8FAFB; border-bottom: 2px solid #E5E7EB;">
              <th style="padding: 12px 16px; text-align: center; font-weight: 600; color: #6B7280;">Rank</th>
              <th style="padding: 12px 16px; text-align: left; font-weight: 600; color: #6B7280;">Name</th>
              <th style="padding: 12px 16px; text-align: center; font-weight: 600; color: #6B7280;">Won Deals</th>
              <th style="padding: 12px 16px; text-align: right; font-weight: 600; color: #6B7280;">Commission</th>
            </tr>
          </thead>
          <tbody>
            ${rows || '<tr><td colspan="4" style="padding: 24px; text-align: center; color: #9CA3AF;">No data for this period</td></tr>'}
          </tbody>
        </table>
      </div>
      <div style="padding: 16px 32px; background-color: #F8FAFB; border-top: 1px solid #E5E7EB;">
        <p style="margin: 0; font-size: 12px; color: #9CA3AF; text-align: center;">
          Generated by ecoLoop Platform
        </p>
      </div>
    </div>
  </div>
</body>
</html>`;
  }
}
